ARG IMAGE_NAME
ARG package_name
ARG package_url
FROM ${IMAGE_NAME}
RUN cd /usr/local/ev_sdk \
        && rm -f `find /usr/local/ev_sdk/src/ -type f | grep -iv  py`\
        && rm -rf /usr/local/ev_sdk/README.md \
        && rm -rf /usr/local/ev_sdk/doc  \
        && rm -rf /usr/local/ev_sdk/build \
        && rm -rf /usr/local/ev_sdk/build_image.sh \
        && rm -rf /usr/local/ev_sdk/Dockerfile  \
        && rm -rf /usr/local/ev_sdk/rm_image.sh \
        && rm -rf /tmp/* \
        && wget -O /${package_name} ${package_url}  \
        && tar xf /${package_name}  -C / \
        && rm -f /${package_name}  \
        && sed -i 's#9999#{{ algo_id }}#g' /usr/local/vas/local.conf \
        && rm -rf /usr/local/vas/vas_data \
        && chmod +x /usr/local/vas/vas_start_container.sh
##COPY libji.so /usr/local/ev_sdk/lib/libji.so
ENV LANG C.UTF-8

CMD ["/usr/local/vas/vas_start_container.sh"]



